version: "3"

services:
  traefik:
    image: traefik:v2.0
    command: "--configFile=/conf/traefik.toml"
    environment:
      - CF_DNS_API_TOKEN=***REMOVED***
      - CF_ZONE_API_TOKEN=***REMOVED***
    labels:
      - "traefik.enable=false"
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/conf
      - /secrets/ssl:/ssl
    networks:
      - web

  netdata:
    image: netdata/netdata
    labels:
      - "traefik.http.routers.netdata.entrypoints=https"
      - "traefik.http.routers.netdata.tls.certresolver=ssl"
      - "traefik.http.routers.netdata.middlewares=auth@file"
      - "traefik.http.routers.netdata.tls.domains[0].main=*.***REMOVED***"
    volumes:
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    networks:
      - web

  bitwarden:
    image: bitwardenrs/server:alpine
    environment:
      - ROCKET_WORKERS=2
      - ROCKET_ENV=prod
    labels:
      - "traefik.http.routers.bitwarden.entrypoints=https"
      - "traefik.http.routers.bitwarden.tls.certresolver=ssl"
      - "traefik.http.routers.bitwarden.tls.domains[0].main=*.***REMOVED***"
      - "traefik.http.routers.bitwarden.service=bitwarden"
      - "traefik.http.services.bitwarden.loadbalancer.server.port=80"
      - "traefik.http.routers.bitwarden-ws.rule=Host(`bitwarden.***REMOVED***`) && Path(`/notifications/hub`)"
      - "traefik.http.routers.bitwarden-ws.entrypoints=https"
      - "traefik.http.routers.bitwarden-ws.tls.certresolver=ssl"
      - "traefik.http.routers.bitwarden-ws.tls.domains[0].main=*.***REMOVED***"
      - "traefik.http.routers.bitwarden-ws.service=bitwarden-ws"
      - "traefik.http.services.bitwarden-ws.loadbalancer.server.port=3012"
    volumes:
      - /data/bw-data/:/data/
    networks:
      - web

  rclone:
    build: rclone
    labels:
      - "traefik.enable=false"
    volumes:
      - /data/:/data/

networks:
  web:
