version: "3"

services:
  traefik:
    image: traefik:2.0
    command: "--configFile=/conf/traefik.toml"
    environment:
      - CF_DNS_API_TOKEN=***REMOVED***
      - CF_ZONE_API_TOKEN=***REMOVED***
    labels:
      - "traefik.enable=false"
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/conf
      - /secrets/ssl:/ssl
    networks:
      - web

  bitwarden:
    image: bitwardenrs/server:alpine
    environment:
      - ROCKET_WORKERS=2
      - ROCKET_ENV=prod
    labels:
      - "traefik.http.routers.bitwarden.entrypoints=https"
      - "traefik.http.routers.bitwarden.tls.certresolver=ssl"
      - "traefik.http.routers.bitwarden.tls.domains[0].main=*.***REMOVED***"
      - "traefik.http.routers.bitwarden.service=bitwarden"
      - "traefik.http.services.bitwarden.loadbalancer.server.port=80"
      - "traefik.http.routers.bitwarden-ws.rule=Host(`bitwarden.***REMOVED***`) && Path(`/notifications/hub`)"
      - "traefik.http.routers.bitwarden-ws.entrypoints=https"
      - "traefik.http.routers.bitwarden-ws.tls.certresolver=ssl"
      - "traefik.http.routers.bitwarden-ws.tls.domains[0].main=*.***REMOVED***"
      - "traefik.http.routers.bitwarden-ws.service=bitwarden-ws"
      - "traefik.http.services.bitwarden-ws.loadbalancer.server.port=3012"
    volumes:
      - /data/bw-data/:/data/
    networks:
      - web

  logs:
    image: amir20/dozzle
    labels:
      - "traefik.http.routers.logs.entrypoints=https"
      - "traefik.http.routers.logs.tls.certresolver=ssl"
      - "traefik.http.routers.logs.middlewares=auth@file"
      - "traefik.http.services.logs.loadbalancer.server.port=8080"
      - "traefik.http.routers.logs.tls.domains[0].main=*.***REMOVED***"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web

  rclone:
    build: rclone
    labels:
      - "traefik.enable=false"
    volumes:
      - /data/:/data/

networks:
  web:
