[http.middlewares]
  [http.middlewares.auth.basicAuth]
    users = ["***REMOVED***"]

  [http.middlewares.httpsredirect.redirectScheme]
    scheme = "https"

  [http.middlewares.githubredirect.redirectRegex]
    regex = ".*"
    replacement = "https://github.com/nrjais"
    permanent = true

  [http.middlewares.wwwredirect.redirectRegex]
    regex = ".*"
    replacement = "https://***REMOVED***"
    permanent = true

[http.routers]
  [http.routers.redirecttohttps]
    entryPoints = ["http"]
    middlewares = ["httpsredirect"]
    rule = "HostRegexp(`{host:.+}`)"
    service = "noop"

  [http.routers.redirecttogithub]
    entryPoints = ["https"]
    middlewares = ["githubredirect"]
    rule = "Host(`github.***REMOVED***`)"
    service = "noop"
    [http.routers.redirecttogithub.tls]
      certResolver = "ssl"
    [[http.routers.redirecttogithub.tls.domains]]
      main = "*.***REMOVED***"

  [http.routers.wwwredirect]
    entryPoints = ["https"]
    middlewares = ["wwwredirect"]
    rule = "Host(`www.***REMOVED***`)"
    service = "noop"
    [http.routers.wwwredirect.tls]
      certResolver = "ssl"
    [[http.routers.wwwredirect.tls.domains]]
      main = "*.***REMOVED***"

  [http.routers.api]
    entryPoints = ["https"]
    middlewares = ["auth"]
    rule = "Host(`traefik.***REMOVED***`)"
    service = "api@internal"
    [http.routers.api.tls]
      certResolver = "ssl"
    [[http.routers.redirecttogithub.tls.domains]]
      main = "*.***REMOVED***"

[http.services]
  [http.services.noop.loadBalancer]
    [[http.services.noop.loadBalancer.servers]]
      url = ""

