name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Deploy and restart
      uses: appleboy/ssh-action@v0.0.2
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.AWS_KEY }}
        script: |
          cat /home/ubuntu/scripts/todo
